spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url : jdbc:sqlserver://localhost;databaseName=CapstoneCRM;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: anushreepal.16027@gmail.com
    password: xulr rfav ajib mcek
    protocol: smtp
    properties:
        mail:
            smtp:
                auth: true
                starttls:
                  enable: true
                ssl:
                  trust: smtp.gmail.com


server:
  port: 8091
#  context-path: /api/v1/sample